import Head from 'next/head'
import Nav from '../components/Nav'
import Home from '../components/Home'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Index() {
  return (
    <>

      <Head>
        <title>NextJs Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Home />
    </>
  )
}
